import test from 'node:test';import assert from 'node:assert/strict';
import {csvRecords,cleanGames,featuresFor,publicationEligibility,matchingProviderEvent,LAG} from '../lib/nba.js';
import {train} from '../src/model.js';
const game=(i,team='Boston Celtics')=>({id:String(i),season:2026,date:new Date(Date.UTC(2026,0,1+i)).toISOString(),home:team,away:'Atlanta Hawks',complete:true,homeScore:110,awayScore:100});
test('Quoted CSV source fields preserve embedded commas, quotes and newlines',()=>{assert.deepEqual(csvRecords('id,date,note\n1,2026-01-01,"a,b\n""quoted"""\n')[0],{id:'1',date:'2026-01-01',note:'a,b\n"quoted"'});assert.throws(()=>csvRecords('id,date\n1,"broken'));});
test('Pregame features ignore future outcomes, overlapping games and other seasons',()=>{const history=Array.from({length:12},(_,i)=>game(i));const target={...game(15),complete:false};const before=featuresFor(target,history);assert.ok(before);assert.deepEqual(featuresFor(target,[...history,{...game(14),homeScore:1000},{...game(20),homeScore:1000},{...game(10),id:'old',season:2025,homeScore:1000}]),before);assert.equal(featuresFor(target,history.slice(0,9)),null);});
test('Training coefficients and scaling exclude the holdout',()=>{const rows=Array.from({length:120},(_,i)=>({date:new Date(Date.UTC(2025,0,i+1)).toISOString(),x:[i%7,i%4],y:i%2}));const a=train(rows,90),b=train(rows.map((r,i)=>i<90?r:{...r,x:[1000,-1000],y:1-r.y}),90);assert.deepEqual(a.weights,b.weights);assert.deepEqual(a.means,b.means);assert.deepEqual(a.sd,b.sd);});
test('Stale offseason and untested models cannot pass publication gates',()=>{const target={...game(30),complete:false};const report={model:{holdoutCount:20,metrics:{brier:.3,baselineBrier:.25},ranges:[[-100,100],[-1,1]]}};assert.equal(publicationEligibility(report,target,Array.from({length:12},(_,i)=>game(i)),Date.parse(target.date)-3600000).eligible,false);});
test('Source cleaning rejects future finals, neutral sites, non-NBA and conflicting IDs',()=>{const base={id:'1',date:'2026-01-01T00:00Z',season:'2026',season_type:'2',neutral_site:'false',time_valid:'true',status_type_completed:'true',status_type_name:'STATUS_FINAL',home_display_name:'Boston Celtics',away_display_name:'Atlanta Hawks',home_score:'110',away_score:'100'};const now=Date.parse(base.date)+LAG+1;assert.equal(cleanGames([base],now).games.length,1);for(const changed of [{neutral_site:'true'},{home_display_name:'Team Shaq'},{date:'2027-01-01T00:00Z'}])assert.equal(cleanGames([{...base,...changed}],now).games.length,0);assert.throws(()=>cleanGames([base,{...base,home_score:'120'}],now));});

test('Provider identity requires exact teams and start time, with explicit Clippers alias',()=>{const g={home:'LA Clippers',away:'Boston Celtics',date:'2026-11-01T20:00:00.000Z'};const e={league:'NBA',id:'abc',home:'Los Angeles Clippers',away:'Boston Celtics',eventStart:g.date};assert.equal(matchingProviderEvent(g,[e]),e);assert.equal(matchingProviderEvent(g,[{...e,eventStart:'2026-11-01T21:00:00Z'}]),undefined);assert.equal(matchingProviderEvent(g,[{...e,away:'Atlanta Hawks'}]),undefined);});
