import test from 'node:test';import assert from 'node:assert/strict';import {americanOdds,normalizeOdds,SPORT_KEYS} from '../lib/odds.js';import {createOddsHandler,cacheSeconds} from '../api/odds.js';
const fixture=[{id:'abc123',home_team:'Home',away_team:'Away',commence_time:'2026-10-02T20:00:00Z',bookmakers:[{title:'Example Book',last_update:'2026-10-01T20:00:00Z',markets:[{key:'h2h',outcomes:[{name:'Home',price:2},{name:'Away',price:3},{name:'Draw',price:4}]}]}]}];
function res(){return{headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(v){this.body=v;return this}};}
function provider(){return{ok:true,status:200,headers:{get(){return'100'}},async text(){return JSON.stringify(fixture)}};}
test('moneyline normalization preserves draws and bookmaker timestamps',()=>{const m=normalizeOdds(fixture,'Premier League')[0];assert.equal(m.outcomes.length,3);assert.equal(m.outcomes[2].name,'Draw');assert.equal(m.outcomes[0].implied,.5);assert.equal(m.bookmaker,'Example Book');assert.equal(americanOdds(1.5),-200);assert.equal(americanOdds(3),200);assert.equal(normalizeOdds([{...fixture[0],bookmakers:[]}],'NBA').length,0);assert.equal(Object.keys(SPORT_KEYS).length,13);});
test('missing key causes no provider request',async()=>{let called=false;const h=createOddsHandler({env:{},fetchImpl:async()=>{called=true}}),r=res();await h({method:'GET',query:{}},r);assert.equal(called,false);assert.equal(r.body.enabled,false);});
test('allowlist rejects unknown sports and client key parameters',async()=>{const h=createOddsHandler({env:{ODDS_API_KEY:'test-only'},fetchImpl:async()=>{throw Error('should not call')}});for(const query of [{league:'unknown'},{league:'NBA',apiKey:'untrusted'},{league:['NBA','NFL']}]){const r=res();await h({method:'GET',query},r);assert.equal(r.code,400);}});
test('server key stays private; league results are cached',async()=>{let calls=0;const h=createOddsHandler({env:{ODDS_API_KEY:'test-key-never-return',ODDS_CACHE_SECONDS:'86400'},store:new Map(),inflight:new Map(),fetchImpl:async(url)=>{calls++;assert.equal(url.hostname,'api.the-odds-api.com');assert.equal(url.searchParams.get('regions'),'us');assert.equal(url.searchParams.get('markets'),'h2h');assert.equal(url.searchParams.get('apiKey'),'test-key-never-return');return provider();}});const a=res(),b=res();await h({method:'GET',query:{league:'NBA'}},a);await h({method:'GET',query:{league:'NBA'}},b);assert.equal(calls,1);assert.equal(a.code,200);assert.equal(JSON.stringify(a).includes('test-key-never-return'),false);assert.equal(a.headers['Cache-Control'],'public, max-age=0, s-maxage=86400');assert.equal(a.body.markets[0].type,'sportsbook-odds');});
test('concurrent requests share a provider call',async()=>{let calls=0;const h=createOddsHandler({env:{ODDS_API_KEY:'test'},store:new Map(),inflight:new Map(),fetchImpl:async()=>{calls++;await new Promise(r=>setTimeout(r,5));return provider()}});await Promise.all([h({method:'GET',query:{league:'NFL'}},res()),h({method:'GET',query:{league:'NFL'}},res())]);assert.equal(calls,1);});
test('cache refresh cannot be configured below 30 minutes',()=>{assert.equal(cacheSeconds('1'),86400);assert.equal(cacheSeconds('1800'),1800);assert.equal(cacheSeconds('NaN'),86400);});
test('provider errors do not disclose upstream URLs or keys',async()=>{const h=createOddsHandler({env:{ODDS_API_KEY:'private-test'},store:new Map(),inflight:new Map(),fetchImpl:async()=>{throw Error('URL contains private-test')}}),r=res();await h({method:'GET',query:{league:'NBA'}},r);assert.equal(r.code,503);assert.equal(JSON.stringify(r).includes('private-test'),false);});
