import test from 'node:test';import assert from 'node:assert/strict';
import {createGamesHandler,normalizeGames} from '../api/games.js';
import {appendEntry,publicArchive,validateLedger,preservePrefix,gradeScore} from '../lib/predictions.js';
import {train,predict,simulate} from '../src/model.js';
const time='2026-10-02T12:00:00.000Z';
const editorial={id:'forecast-1',kind:'editorial',league:'NBA',eventId:'event1',event:'Away at Home',home:'Home',away:'Away',selection:'Home',eventStart:'2026-10-03T12:00:00Z',publishedAt:time,inputAsOf:'2026-10-02T10:00:00Z',dataSource:'Test provenance',dataPermissionReference:'Test only',rationale:'Example analysis for automated tests, never published.',settlementRule:'match-winner-including-overtime'};
const forecast=p=>appendEntry([],{entryId:'entry-1',type:'forecast',forecast:p},time);
function response(){return{headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(data){this.body=data;return this}};}
test('schedule remains closed without a key; malformed requests rejected',async()=>{let calls=0;const h=createGamesHandler({env:{},fetchImpl:async()=>calls++});const a=response();await h({method:'GET',query:{league:'NBA'}},a);assert.equal(a.body.enabled,false);assert.equal(calls,0);for(const q of [{league:'__proto__'},{league:['NBA']},{league:'NBA',apiKey:'x'}]){const r=response();await h({method:'GET',query:q},r);assert.equal(r.code,400);}});
test('schedule normalizes, caches and keeps keys private',async()=>{let calls=0;const h=createGamesHandler({env:{ODDS_API_KEY:'secret-test'},store:new Map(),inflight:new Map(),fetchImpl:async u=>{calls++;assert.equal(u.hostname,'api.the-odds-api.com');assert.equal(u.pathname,'/v4/sports/basketball_nba/events');return{ok:true,text:async()=>JSON.stringify([{id:'e1',home_team:'Home',away_team:'Away',commence_time:'2026-10-03T12:00:00Z'}])};}});const a=response(),b=response();await h({method:'GET',query:{league:'NBA'}},a);await h({method:'GET',query:{league:'NBA'}},b);assert.equal(calls,1);assert.equal(a.body.games[0].home,'Home');assert.equal(JSON.stringify(a).includes('secret-test'),false);assert.equal(normalizeGames([{id:'bad'}],'NBA').length,0);});
test('forecast and losing resolution survive; tampering/deletion rejected',()=>{const first=forecast(editorial),result=appendEntry([first],{entryId:'result-1',type:'resolution',predictionId:'forecast-1',result:'loss',source:'Test score',reason:'Home lost',resolvedAt:'2026-10-03T16:00:00Z',correctsEntryId:null},'2026-10-03T17:00:00Z');const archive=publicArchive([first,result]);assert.equal(archive.predictions.length,1);assert.equal(archive.resolutions[0].result,'loss');assert.throws(()=>validateLedger([{...first,forecast:{...editorial,selection:'Away'}}]));assert.throws(()=>preservePrefix(JSON.stringify(first)+'\n',''));assert.doesNotThrow(()=>preservePrefix(JSON.stringify(first)+'\n',JSON.stringify(first)+'\n'+JSON.stringify(result)+'\n'));});
test('publication rejects post-event timestamps and editorial model claims',()=>{assert.throws(()=>forecast({...editorial,eventStart:time}));assert.throws(()=>forecast({...editorial,probability:.8}));});
test('model archive requires reproduced forecast and actual simulation evidence',()=>{const rows=Array.from({length:200},(_,i)=>({date:new Date(Date.UTC(2024,0,i+1)).toISOString(),x:[i%2?1:-1,(i%3)-1],y:i%2})),model=train(rows),features=[1,0],probability=predict(model,features);const p={...editorial,kind:'model',model,features,probability,synthetic:false,datasetHash:'a'.repeat(64),simulation:simulate(probability)};assert.doesNotThrow(()=>forecast(p));assert.throws(()=>forecast({...p,probability:.1}));assert.throws(()=>forecast({...p,synthetic:true}));assert.throws(()=>forecast({...p,simulation:{...p.simulation,yes:1}}));});
test('resolution correction preserves prior loss and must reference it',()=>{const f=forecast(editorial),r=appendEntry([f],{entryId:'r1',type:'resolution',predictionId:editorial.id,result:'loss',source:'Test',reason:'Initial result',resolvedAt:'2026-10-03T16:00:00Z'},'2026-10-03T17:00:00Z');assert.throws(()=>appendEntry([f,r],{entryId:'r2',type:'resolution',predictionId:editorial.id,result:'win',source:'Test',reason:'Correction',resolvedAt:'2026-10-03T16:00:00Z'},'2026-10-03T18:00:00Z'));const c=appendEntry([f,r],{entryId:'r2',type:'resolution',predictionId:editorial.id,result:'win',source:'Test',reason:'Score provider correction',resolvedAt:'2026-10-03T16:00:00Z',correctsEntryId:'r1'},'2026-10-03T18:00:00Z');assert.equal(publicArchive([f,r,c]).resolutions.length,2);});
test('grader requires exact event and completed scores; ambiguous soccer remains pending',()=>{const e={id:'event1',home_team:'Home',away_team:'Away',completed:true,scores:[{name:'Home',score:'99'},{name:'Away',score:'101'}]};assert.equal(gradeScore(editorial,e),'loss');assert.equal(gradeScore(editorial,{...e,completed:false}),null);assert.equal(gradeScore(editorial,{...e,home_team:'Other'}),null);assert.equal(gradeScore({...editorial,league:'La Liga'},e),null);assert.equal(gradeScore(editorial,{...e,scores:[{name:'Home',score:'99'},{name:'Home',score:'100'}]}),null);});
import {launchPlan,planForSubscription} from '../src/plans.js';
test('founding catalog retains versioned monthly price and keeps billing inactive',()=>{const p=launchPlan();assert.equal(p.amountCents,299);assert.equal(p.trialDays,14);assert.equal(p.billingEnabled,false);assert.equal(planForSubscription({planVersion:'pro-founding-v1'}),p);assert.equal(planForSubscription({planVersion:'unknown'}),null);});
