import test from 'node:test';import assert from 'node:assert/strict';import {parseCSV,train,predict,simulate,ledgerMetrics} from '../src/model.js';import handler,{normalizeFeed} from '../api/markets.js';
function rows(){return Array.from({length:200},(_,i)=>({date:new Date(Date.UTC(2024,0,i+1)).toISOString(),x:[i%2?1:-1,(i%3)-1],y:i%2}));}
test('simulation reproducibility, counts and endpoints',()=>{assert.deepEqual(simulate(.6),simulate(.6));const r=simulate(.6,100000);assert.equal(r.yes+r.no,100000);assert.ok(Math.abs(r.frequency-.6)<.01);assert.equal(simulate(0).yes,0);assert.equal(simulate(1).yes,10000);assert.throws(()=>simulate(NaN));assert.throws(()=>simulate(.5,1));});
test('training separates chronological holdout and learns signal',()=>{const m=train(rows());assert.equal(m.trainingCount,160);assert.equal(m.holdoutCount,40);assert.ok(m.metrics.brier<m.metrics.baselineBrier);assert.ok(predict(m,[1,0])>.8);assert.ok(predict(m,[-1,0])<.2);});
test('holdout changes cannot change model parameters',()=>{const r=rows(),a=train(r);r.slice(160).forEach(x=>x.y=1-x.y);const b=train(r);assert.deepEqual(a.weights,b.weights);assert.deepEqual(a.means,b.means);});
test('CSV rejects missing values, reversed dates and single class',()=>{const csv='date,feature_a,feature_b,outcome\n'+rows().map(r=>r.date.slice(0,19)+'Z,'+r.x.join(',')+','+r.y).join('\n');assert.equal(parseCSV(csv).length,200);assert.throws(()=>parseCSV(csv.replace(',1,0,1',',,0,1')));assert.throws(()=>train(rows().map(r=>({...r,y:1}))));});
test('unresolved entries excluded from metrics',()=>{assert.deepEqual(ledgerMetrics([{probability:.9,outcome:1},{probability:.1,outcome:null}]),{count:1,brier:(.9-1)**2});});
test('feed rejects nonnumeric and unsafe records',()=>{assert.throws(()=>normalizeFeed({source:'x',attribution:'x',markets:[{id:'x',question:'q',category:'Sports',ask:'0.5'}]}));assert.equal(normalizeFeed({source:'x',attribution:'x',markets:[]}).markets.length,0);});
test('feed defaults closed without permission',async()=>{const req={method:'GET'},res={status(c){this.code=c;return this;},json(v){this.body=v;return this;}};await handler(req,res);assert.equal(res.code,200);assert.equal(res.body.enabled,false);});
