import test from 'node:test';import assert from 'node:assert/strict';
import {cleanSoccer,soccerForm,matchingSoccerFixture,buildSoccerReport} from '../lib/soccer.js';
import {competitionDay,soccerSeason,sourceHealth,canonicalSoccer} from '../src/soccer-data.js';
import {refreshSoccer} from '../scripts/soccer-context.mjs';
import {formCard} from '../src/team-form.js';
import {findContext} from '../src/matchup-data.js';
const now=Date.parse('2026-10-03T21:00:00Z');
function data(){const matches=[];for(let i=0;i<20;i++)for(let j=i+1;j<20;j++)matches.push({date:'2026-08-21',team1:'Team '+i,team2:'Team '+j,score:{ft:[i%3,j%2]}});return{name:'English Premier League 2026/27',matches};}
test('Soccer source accepts explicit full-time score variants and 0–0 draws, excludes recent/future/invalid dates',()=>{const d=data();d.matches.push({date:'2026-10-01',team1:'Team 1',team2:'Team 2',score:[0,0]},{date:'2026-09-21',team1:'Team 1',team2:'Team 2',score:[0,0]},{date:'2026-02-30',team1:'Team 1',team2:'Team 2',score:[1,0]},{date:'2026-10-10',team1:'Team 1',team2:'Team 2',score:[9,0]},{date:'2026-09-30',team1:'Team 1',team2:'Team 2',score:{ht:[1,0]}});const r=cleanSoccer(d,'Premier League','2026-27',now);assert.equal(r.games.find(g=>g.sourceDate==='2026-09-21').homeScore,0);assert.equal(r.games.some(g=>g.sourceDate==='2026-10-01'),false);assert.equal(r.games.some(g=>g.sourceDate==='2026-10-10'&&g.complete),false);assert.equal(r.games.find(g=>g.sourceDate==='2026-09-30').complete,false);assert.equal(r.excluded,3);});
test('Conflicting results, incomplete coverage and wrong seasons fail closed',()=>{const d=data();d.matches.push({...d.matches[0],score:{ft:[9,9]}});assert.throws(()=>cleanSoccer(d,'Premier League','2026-27',now),/Conflicting/);assert.throws(()=>cleanSoccer({name:d.name,matches:d.matches.slice(0,10)},'Premier League','2026-27',now),/Incomplete/);assert.throws(()=>cleanSoccer(data(),'Premier League','2025-26',now),/Unsupported/);assert.throws(()=>cleanSoccer({...data(),name:'Spain Primera División 2026/27'},'Premier League','2026-27',now),/Unsupported/);});
test('Soccer aliases are explicit; competition days honor local DST and UTC midnight',()=>{assert.equal(canonicalSoccer('FC Barcelona','La Liga'),'Barcelona');assert.equal(canonicalSoccer('Barcelona reserves','La Liga'),'Barcelona reserves');assert.equal(competitionDay('2026-10-10T23:00:00Z','La Liga'),'2026-10-11');assert.equal(competitionDay('2026-12-10T23:00:00Z','La Liga'),'2026-12-11');assert.equal(soccerSeason(Date.parse('2026-06-30')),'2025-26');assert.equal(soccerSeason(Date.parse('2026-07-01')),'2026-27');});
test('Fixture match requires unique explicit teams and local date, never reversed/opponent substitutions',()=>{const e={league:'La Liga',home:'Barcelona',away:'Real Madrid',eventStart:'2026-10-10T19:00:00Z'},g={home:'Barcelona',away:'Real Madrid',sourceDate:'2026-10-10'};assert.equal(matchingSoccerFixture(e,[g]),g);assert.equal(matchingSoccerFixture(e,[g,g]),null);assert.equal(matchingSoccerFixture(e,[{...g,home:g.away,away:g.home}]),null);assert.equal(matchingSoccerFixture(e,[{...g,sourceDate:'2026-10-11'}]),null);});
test('Descriptive window preserves draws, team perspective, day precision and availability boundaries',()=>{const event={id:'next',season:'2026-27',home:'A',away:'B',date:'2026-10-06T17:00:00Z'},base={complete:true,season:event.season,home:'A',away:'B'};const games=[{...base,id:'tie',date:'2026-10-01T23:59:59.999Z',homeScore:0,awayScore:0},{...base,id:'win',date:'2026-10-02T23:59:59.999Z',homeScore:2,awayScore:1},{...base,id:'recent',date:'2026-10-04T23:59:59.999Z',homeScore:9,awayScore:0},{...base,id:'other-season',date:'2026-09-01T23:59:59.999Z',season:'2025-26',homeScore:8,awayScore:0}];const f=soccerForm(event,games.reverse());assert.equal(f.home.count,2);assert.equal(f.home.ties,1);assert.equal(f.away.losses,1);assert.equal(f.home.averageScored,1);assert.equal(f.home.averageAllowed,.5);assert.equal(f.away.averageScored,.5);assert.equal(f.home.recent[1].result,'D');assert.equal(f.home.recent[0].dateOnly,'2026-10-02');const html=formCard(f.home,'Premier League');assert.match(html,/Wins–draws–losses/);assert.match(html,/datetime="2026-10-02"/);assert.doesNotMatch(html,/11:59/);});
test('Fresh retrieval does not disguise delayed results; outages retain original snapshot timestamps',async()=>{const old={generatedAt:'2026-10-01T12:00:00Z',dataThrough:'2026-09-20',teams:[]};assert.equal(sourceHealth({...old,generatedAt:new Date(now).toISOString()},now).resultsDelayed,true);assert.equal(sourceHealth(old,now).snapshotOverdue,true);const result=await refreshSoccer({now,previous:{leagues:{'Premier League':old}},fetchImpl:async()=>{throw Error('offline');}});assert.equal(result.leagues['Premier League'],old);assert.equal(result.refresh['Premier League'].state,'source-or-validation-error');assert.equal(result.leagues['Premier League'].generatedAt,old.generatedAt);assert.equal(Object.keys(result.leagues).length,1);});
test('Schedule matching stores descriptive evidence only and fails closed on stale schedules or wrong event IDs',()=>{const d=data();d.matches.push({date:'2026-10-10',team1:'Team 1',team2:'Team 2'});const e={id:'provider1',league:'Premier League',home:'Team 1',away:'Team 2',eventStart:'2026-10-10T11:30:00.000Z'},feed={enabled:true,league:e.league,fetchedAt:new Date(now).toISOString(),games:[e]};const report=buildSoccerReport({league:e.league,season:'2026-27',raw:JSON.stringify(d),feed,now});assert.equal(report.upcoming.length,1);assert.equal(report.status,'descriptive-statistics');assert.equal(report.upcoming[0].probability,undefined);assert.equal(report.upcoming[0].model,undefined);assert.equal(findContext({...e,id:'another-id'},report),null);assert.equal(findContext(e,report).eventId,e.id);assert.equal(findContext(e,report).form.home.team,e.home);assert.equal(findContext(e,{...report,generatedAt:'2026-10-11T12:00:00Z'}),null);const stale=buildSoccerReport({league:e.league,season:'2026-27',raw:JSON.stringify(d),feed:{...feed,fetchedAt:'2026-09-01T12:00:00Z'},now});assert.equal(stale.upcoming.length,0);assert.equal(stale.teams.length,20);assert.equal(stale.scheduleState,'schedule-unavailable');});
