import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFile} from 'node:fs/promises';
const sw=await readFile(new URL('../sw.js',import.meta.url),'utf8'),client=await readFile(new URL('../src/app.js',import.meta.url),'utf8');
function worker(fetchImpl=async()=>new Response('network')){
 const handlers={},stored=new Map(),deleted=[],writes=[];let skipped=false,claimed=false;
 const self={location:{origin:'https://tonati.test'},addEventListener:(name,cb)=>handlers[name]=cb,skipWaiting:async()=>{skipped=true;},clients:{claim:async()=>{claimed=true;}}};
 const caches={open:async name=>({put:async(path,response)=>{writes.push({name,path});stored.set(name+path,response);}}),match:async(path,{cacheName})=>stored.get(cacheName+path)?.clone(),keys:async()=>['tonati-offline-v0','tonati-offline-v1','other-product-cache'],delete:async name=>{deleted.push(name);}};
 vm.runInNewContext(sw,{self,caches,fetch:fetchImpl,URL,Response});
 const lifetime=async name=>{let p;handlers[name]({waitUntil:v=>p=v});await p;};
 const request=async(url,mode='navigate',method='GET')=>{let p;handlers.fetch({request:{url,mode,method},respondWith:v=>p=v});return p?await p:null;};
 return{lifetime,request,stored,writes,deleted,state:()=>({skipped,claimed})};
}
test('Worker caches only the connection page and removes only its own older cache',async()=>{const w=worker();await w.lifetime('install');assert.deepEqual(w.writes,[{name:'tonati-offline-v1',path:'/offline.html'}]);assert.equal(w.state().skipped,true);await w.lifetime('activate');assert.deepEqual(w.deleted,['tonati-offline-v0']);assert.equal(w.state().claimed,true);});
test('Online navigation uses the network every time and never stores sports documents',async()=>{let calls=0;const w=worker(async request=>{calls++;return new Response('fresh '+request.url);});for(let i=0;i<2;i++)assert.match(await (await w.request('https://tonati.test/')).text(),/fresh/);assert.equal(calls,2);assert.equal(w.writes.length,0);});
test('Failed navigation shows the connection fallback; APIs and JSON reports are not intercepted',async()=>{const w=worker(async()=>{throw Error('offline');});w.stored.set('tonati-offline-v1/offline.html',new Response('Connection unavailable; no sports data'));assert.match(await (await w.request('https://tonati.test/track-record.html')).text(),/no sports data/);for(const url of ['/api/games?league=NFL','/api/odds?league=NBA','/data/predictions.json','/data/nfl-feed.json','/assets/dashboard.js'])assert.equal(await w.request('https://tonati.test'+url,'cors'),null);assert.equal(await w.request('https://other.test/'),null);assert.equal(await w.request('https://tonati.test/','navigate','POST'),null);});
function app({standalone=false,online=true,frame=false}={}){
 const listeners={},nodes=[],registered=[],button={hidden:true,disabled:false,addEventListener:(name,cb)=>button[name]=cb},state={textContent:''};
 const node=tag=>({tag,children:[],hidden:false,textContent:'',attrs:{},setAttribute(k,v){this.attrs[k]=v;},append(child){this.children.push(child);}});
 const body=node('body');body.classList={toggle:(name,value)=>body[name]=value};const main={before:n=>nodes.push(n)};
 const document={body,createElement:node,querySelector:s=>({'#install-app':button,'#install-state':state,'main':main})[s]||null};
 const window={matchMedia:()=>({matches:standalone}),addEventListener:(name,cb)=>listeners[name]=cb};window.self=window;window.top=frame?{}:window;
 const navigator={onLine:online,serviceWorker:{register:async(...args)=>{registered.push(args);}}};
 vm.runInNewContext(client,{window,navigator,document,location:{protocol:'https:',pathname:'/analytics.html'}});
 return{listeners,button,state,body,nodes,registered};
}
test('Installed phone navigation has an active Lab link; normal sessions and review frames keep site behavior',()=>{const installed=app({standalone:true});assert.equal(installed.body['installed-app'],true);assert.deepEqual(installed.body.children[0].children.map(a=>a.textContent),['Games','Lab','Record']);assert.equal(installed.body.children[0].children[1].attrs['aria-current'],'page');assert.equal(app().body.children.length,0);assert.equal(app({frame:true}).registered.length,0);});
test('Canceled prompts do not claim installation; accepted prompts await real installed confirmation',async()=>{for(const outcome of ['dismissed','accepted']){const a=app();let prevented=false,requested=0;a.listeners.beforeinstallprompt({preventDefault:()=>prevented=true,prompt:async()=>requested++,userChoice:Promise.resolve({outcome})});assert.equal(prevented,true);assert.equal(a.button.hidden,false);await a.button.click();assert.equal(requested,1);assert.equal(a.button.hidden,true);assert.match(a.state.textContent,outcome==='accepted'?/Installation requested/:/Not added/);a.listeners.appinstalled();assert.match(a.state.textContent,/was added/);}});
test('Connection changes label previous snapshots and request refresh instead of claiming fresh data',()=>{const a=app({online:false});assert.equal(a.nodes[0].hidden,false);assert.match(a.nodes[0].textContent,/previously fetched snapshot/);a.listeners.online();assert.match(a.nodes[0].textContent,/Refresh the schedule/);assert.equal(a.registered[0][0],'/sw.js');assert.equal(a.registered[0][1].updateViaCache,'none');});
test('Manifest has stable identity, standalone display and correctly sized PNG icons',async()=>{const manifest=JSON.parse(await readFile(new URL('../manifest.webmanifest',import.meta.url),'utf8'));assert.equal(manifest.id,'/');assert.equal(manifest.start_url,'/');assert.equal(manifest.display,'standalone');for(const icon of manifest.icons){const png=await readFile(new URL('../src/icons/'+icon.src.split('/').at(-1),import.meta.url));assert.equal(png.subarray(1,4).toString(),'PNG');const [w,h]=icon.sizes.split('x').map(Number);assert.equal(png.readUInt32BE(16),w);assert.equal(png.readUInt32BE(20),h);}});
