import {teamNameHtml} from './team-colors.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=p=>(p*100).toFixed(1)+'%';
let archive={predictions:[],resolutions:[]};
function render(){
 const resolved=id=>archive.resolutions.filter(r=>r.predictionId===id).at(-1);
 const all=archive.predictions.filter(p=>Date.parse(p.publishedAt)<=Date.now());
 const model=all.filter(p=>p.kind==='model'),graded=model.filter(p=>['win','loss'].includes(resolved(p.id)?.result));
 const editorial=all.filter(p=>p.kind==='editorial'),edGraded=editorial.filter(p=>['win','loss'].includes(resolved(p.id)?.result));
 const brier=graded.length?graded.reduce((s,p)=>s+(p.probability-(resolved(p.id).result==='win'?1:0))**2,0)/graded.length:null;
 const accuracy=graded.length?graded.filter(p=>(p.probability>=.5)===(resolved(p.id).result==='win')).length/graded.length:null;
 const voids=all.filter(p=>resolved(p.id)?.result==='void').length,pending=all.filter(p=>!resolved(p.id)).length;
 $('public-metrics').innerHTML=`<div class="card"><div class="small">MODEL BRIER SCORE</div><div class="metric-value">${brier===null?'—':brier.toFixed(3)}</div><p class="small">${graded.length} resolved model forecasts · lower is better<br>Threshold accuracy (0.5): ${accuracy===null?'—':pct(accuracy)}</p></div><div class="card"><div class="small">EDITORIAL SELECTION HIT RATE</div><div class="metric-value">${edGraded.length?pct(edGraded.filter(p=>resolved(p.id).result==='win').length/edGraded.length):'—'}</div><p class="small">${edGraded.length} resolved editorial selections · excludes voids</p></div><div class="card"><div class="small">PUBLISHED RECORDS</div><div class="metric-value">${all.length}</div><p class="small">${pending} pending · ${voids} void<br>No outcome or profit guarantee</p></div>`;
 const kind=$('archive-kind').value,result=$('archive-result').value,list=all.filter(p=>(kind==='all'||p.kind===kind)&&(result==='all'||(resolved(p.id)?.result||'pending')===result));
 $('public-archive').innerHTML=list.length?list.slice().reverse().map(p=>{const r=resolved(p.id),history=archive.resolutions.filter(x=>x.predictionId===p.id);return `<article class="card"><div class="row"><span class="pill">${p.kind==='model'?'MODEL FORECAST':'EDITORIAL SELECTION'} · ${esc(p.league)}</span><strong>${esc((r?.result||'pending').toUpperCase())}</strong></div><h3>${teamNameHtml(p.away,p.league)} at ${teamNameHtml(p.home,p.league)}</h3><p><strong>${p.kind==='model'?'Probability target':'Selection'}: ${teamNameHtml(p.selection,p.league)}${p.handicap!==undefined?' '+(p.handicap>0?'+':'')+esc(p.handicap)+' runs':''}</strong>${p.kind==='model'?' · Model probability '+pct(p.probability):''}</p><p>${esc(p.rationale)}</p><p class="small">Published ${esc(new Date(p.publishedAt).toLocaleString())} · Event ${esc(new Date(p.eventStart).toLocaleString())}<br>Settlement: ${esc(p.settlementRule)} · Source: ${esc(p.dataSource)} · Inputs as of ${esc(p.inputAsOf)}</p>${p.kind==='model'?`<p class="small">Model ${esc(p.model.version)} · ${p.model.trainingCount} training / ${p.model.holdoutCount} holdout observations · ${p.simulation.n.toLocaleString()} simulations · seed ${p.simulation.seed}</p>`:''}<details><summary>Publication evidence${history.length>1?' & correction history':''}</summary><p class="small">ID: ${esc(p.id)}<br>Record hash: ${esc(p.recordHash)}<br>Permission reference: ${esc(p.dataPermissionReference)}</p>${history.map(x=>`<p class="small">${esc(x.result.toUpperCase())} · ${esc(x.recordedAt)} · ${esc(x.source)}<br>${esc(x.reason)}${x.correctsEntryId?'<br>Correction of '+esc(x.correctsEntryId):''}</p>`).join('')}${p.kind==='model'?`<pre>${esc(JSON.stringify({model:p.model,features:p.features,datasetHash:p.datasetHash,simulation:p.simulation},null,2))}</pre>`:''}</details></article>`;}).join(''):'<div class="empty"><h3>No publications in this view.</h3><p>Forecasts will appear here when published before their events. No historical results have been invented.</p></div>';
}
$('archive-kind').onchange=render;$('archive-result').onchange=render;
fetch('/data/predictions.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{archive=data;render();}).catch(()=>{$('public-archive').innerHTML='<div class="empty">The public archive could not be loaded. Please try again later.</div>';});
