import {teamNameHtml} from './team-colors.js';
import {LEAGUES} from './sports.js';
import {selectedPick,currentPick} from './daily-pick.js';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),pct=v=>(v*100).toFixed(1)+'%';
const localDay=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const time=v=>new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'});
let games=[],odds=[],records=[],demo=false,watchOnly=false,version=0,oddsVersion=0,connection='loading';
let watches=[];try{watches=JSON.parse(localStorage.getItem('unpredicted-watch-v1')||'[]').filter(x=>typeof x==='string');}catch{}
$('game-day').value=localDay(new Date());
try{const old=localStorage.getItem('tonati-league');if(LEAGUES.includes(old))$('league').value=old;}catch{}
function render(){
 const league=$('league').value,term=$('search').value.trim().toLowerCase(),day=$('game-day').value;
 $('game-context').textContent=`${league} · ${day||'all dates'} · your local time`;
 const list=games.filter(g=>(demo||!day||localDay(new Date(g.eventStart))===day)&&`${g.home} ${g.away}`.toLowerCase().includes(term)&&(!watchOnly||watches.includes(g.id)||watches.includes('odds-'+g.id)));
 $('games').innerHTML=list.map(g=>{
 const market=odds.find(o=>o.id==='odds-'+g.id),prediction=records.find(p=>p.eventId===g.id&&p.kind==='model'&&p.league===league&&p.publishedAt<=new Date().toISOString());
 return `<article class="game-card"><div class="row"><span class="pill">${esc(league)}${demo?' · FICTIONAL DEMO':''}</span><span class="small">${demo?'No real event':esc(time(g.eventStart))}</span></div><div class="team-row"><span class="team-token" aria-hidden="true">${esc(g.away.slice(0,2).toUpperCase())}</span>${teamNameHtml(g.away,league)}</div><div class="team-row"><span class="team-token" aria-hidden="true">${esc(g.home.slice(0,2).toUpperCase())}</span>${teamNameHtml(g.home,league)} <span class="small">HOME</span></div><div class="game-metrics"><div><span class="small">MODEL PROBABILITY</span><strong>${prediction?pct(prediction.probability):'Not published'}</strong><span class="small">${prediction?esc(prediction.selection):'No invented estimate'}</span></div><div><span class="small">MARKET CONTEXT</span><strong>${market?'Available':'Not loaded'}</strong><span class="small">${market?'Bookmaker prices':'Separate from model analysis'}</span></div></div>${prediction?`<p class="small">Model ${esc(prediction.model.version)} · Published ${esc(time(prediction.publishedAt))}</p><p>${esc(prediction.rationale)}</p><a class="text-link" href="/track-record.html">Inspect forecast record</a>`:''}${market?`<details open><summary>Market-implied probabilities</summary><p class="small">${esc(market.bookmaker)} · Quote updated ${esc(time(market.updatedAt))}</p>${market.outcomes.map(o=>`<div class="market-row"><span>${teamNameHtml(o.name,league)}</span><strong>${pct(o.implied)}</strong><span>${o.american>0?'+':''}${o.american}</span></div>${prediction&&prediction.selection===o.name?`<p class="small">Model minus raw market probability: ${((prediction.probability-o.implied)*100).toFixed(1)} percentage points. Margin, fees and timing differences are not adjusted.</p>`:''}`).join('')}<p class="small">Includes bookmaker margin; not an independent AI forecast.</p></details>`:''}<details><summary>Matchup & data notes</summary><p>${demo?'These team names are fictional and do not represent a current game.':'Event information from The Odds API. Scheduled start time does not confirm a game is in play or final. Injury reports, lineups and team ratings are not connected yet.'}</p><p class="small">Independent model analysis is published only when a documented model, pregame inputs and data provenance are available.</p></details><div class="actions"><button class="secondary" data-watch="${esc(g.id)}" aria-pressed="${watches.includes(g.id)}">${watches.includes(g.id)?'Watching':'Watch game'}</button><a class="text-link" href="/analytics.html">Research in the lab</a></div></article>`;
 }).join('')||`<div class="empty"><h3>${connection==='loading'?'Loading schedule…':connection==='inactive'?'Game data is not connected yet.':connection==='error'?'Schedule temporarily unavailable.':'No games match this view.'}</h3><p>${connection==='inactive'?'The provider connection is awaiting activation. No fictional games are shown as current.':connection==='error'?'Try refreshing the schedule later. No replacement events have been fabricated.':'Try another date, league or search. Event coverage varies by season and provider.'}</p><p class="small">You can still train a model and run simulations in the free Analysis Lab.</p><a class="button secondary" href="/analytics.html">Open Analysis Lab</a></div>`;
}
async function loadGames(){
 const v=++version;++oddsVersion;$('load-odds').disabled=false;demo=false;odds=[];games=[];connection='loading';$('feed-label').textContent='CHECKING SCHEDULE';$('feed-status').textContent='Loading the selected league…';render();
 try{const response=await fetch(`/api/games?league=${encodeURIComponent($('league').value)}`),data=await response.json();if(v!==version)return;if(!response.ok)throw Error();connection=data.enabled?'ready':'inactive';games=data.games||[];
 $('feed-label').textContent=data.enabled?'CACHED SCHEDULE':'DATA NOT CONNECTED';$('feed-status').textContent=data.enabled?`${data.source} · Retrieved ${time(data.fetchedAt)} · Up to 1-hour cache. Not live scores.`:'The current sports-data connection is inactive. Demo examples are optional and clearly labeled.';
 }catch{if(v!==version)return;connection='error';$('feed-label').textContent='SCHEDULE UNAVAILABLE';$('feed-status').textContent='The schedule could not be retrieved.';}render();
}
async function loadOdds(){
 if(demo){$('feed-status').textContent='Return to the real schedule before requesting market context.';return;}
 const v=++oddsVersion,league=$('league').value;$('load-odds').disabled=true;$('feed-status').textContent='Loading cached market context…';
 try{const response=await fetch(`/api/odds?league=${encodeURIComponent(league)}`),data=await response.json();if(v!==oddsVersion)return;if(!response.ok)throw Error();odds=data.markets||[];
 if(data.enabled){if(!games.length)games=odds.map(m=>({id:m.id.replace(/^odds-/,''),home:m.home||m.question.split(' at ')[1],away:m.away||m.question.split(' at ')[0],eventStart:m.eventStart}));connection='ready';$('feed-status').textContent=`${data.source} · Retrieved ${time(data.fetchedAt)} · Cache ${Math.round(data.cacheSeconds/3600)} hours. Individual quote times appear on each game. Odds are not AI forecasts.`;}else $('feed-status').textContent='Market context is awaiting provider activation. No fabricated odds are shown.';
 }catch{if(v!==oddsVersion)return;$('feed-status').textContent='Market context is temporarily unavailable. The schedule remains accessible.';}
 finally{if(v===oddsVersion){$('load-odds').disabled=false;render();}}
}
$('load-games').onclick=loadGames;$('load-odds').onclick=loadOdds;
$('league').onchange=()=>{try{localStorage.setItem('tonati-league',$('league').value);}catch{}$('load-odds').disabled=false;loadGames();};
$('game-day').onchange=render;$('search').oninput=render;
$('watch-only').onclick=()=>{watchOnly=!watchOnly;$('watch-only').setAttribute('aria-pressed',String(watchOnly));render();};
$('show-demo').onclick=()=>{++version;++oddsVersion;demo=true;connection='ready';odds=[];$('load-odds').disabled=false;games=[{id:'tonati-demo-'+$('league').value,home:'Fictional Harbor Hawks',away:'Fictional Coast Comets',eventStart:new Date().toISOString()}];$('feed-label').textContent='FICTIONAL DEMO';$('feed-status').textContent='Fictional team names. No actual event, odds, model estimate or recommendation. Refresh schedule to return to provider data.';render();};
$('games').onclick=e=>{const b=e.target.closest('[data-watch]');if(!b)return;const id=b.dataset.watch;try{const next=watches.includes(id)?watches.filter(x=>x!==id):[...watches,id].slice(-200);localStorage.setItem('unpredicted-watch-v1',JSON.stringify(next));watches=next;render();}catch{$('feed-status').textContent='Browser storage is unavailable. This watchlist could not be saved.';}};
function renderPick(p){const pick=currentPick(p);if(!pick)return;$('daily-pick').innerHTML=`<h3>${teamNameHtml(pick.away,pick.league)} at ${teamNameHtml(pick.home,pick.league)}</h3><p><strong>${teamNameHtml(pick.selection,pick.league)}${pick.handicap!==undefined?' '+(pick.handicap>0?'+':'')+esc(pick.handicap)+' runs':''}</strong> · ${esc(pick.league)}</p><p>${esc(pick.rationale)}</p><p class="small">Editorial selection · Published ${esc(time(pick.publishedAt))} · Event ${esc(time(pick.eventStart))}</p><p class="small">${pick.modelPredictionId?'Supporting model record: '+esc(pick.modelPredictionId)+'. See publication history.':'No AI or model support claimed.'} No outcome or profit is guaranteed.</p>`;}
renderPick(selectedPick);
fetch('/data/predictions.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{records=data.predictions||[];renderPick(records.filter(p=>p.kind==='editorial').at(-1));render();}).catch(()=>{});
loadGames();
