import {LEAGUES,matchesLeague} from './sports.js';
import {selectedPick,currentPick} from './daily-pick.js';
import {parseCSV,train,predict,simulate,ledgerMetrics,VERSION} from './model.js';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=p=>(p*100).toFixed(1)+'%';
function read(key){try{const a=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(a)?a:[];}catch{return[];}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value));}
function download(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function hash(value){const data=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(typeof value==='string'?value:JSON.stringify(value)));return [...new Uint8Array(data)].map(x=>x.toString(16).padStart(2,'0')).join('');}
let notebook=read('unpredicted-notebook-v1').filter(r=>r&&typeof r.question==='string'&&Number.isFinite(r.probability)&&r.probability>=0&&r.probability<=1&&typeof r.id==='string').slice(-200);
let watches=read('unpredicted-watch-v1').filter(x=>typeof x==='string').slice(0,200);
const examples=[{"id": "demo-0", "question": "Will fictional Harbor Hawks win their next game?", "league": "NBA", "category": "Sports", "ask": 0.42, "source": "Fictional example"}, {"id": "demo-1", "question": "Will fictional Coast Comets win their next game?", "league": "MLB", "category": "Sports", "ask": 0.48, "source": "Fictional example"}, {"id": "demo-2", "question": "Will fictional Valley Wolves win their next game?", "league": "NFL", "category": "Sports", "ask": 0.54, "source": "Fictional example"}, {"id": "demo-3", "question": "Will fictional Frost Falcons win their next game?", "league": "NHL", "category": "Sports", "ask": 0.6, "source": "Fictional example"}, {"id": "demo-4", "question": "Will fictional Bay Stars win their next game?", "league": "WNBA", "category": "Sports", "ask": 0.66, "source": "Fictional example"}, {"id": "demo-5", "question": "Will fictional Harbor FC win their next game?", "league": "Premier League", "category": "Sports", "ask": 0.42, "source": "Fictional example"}, {"id": "demo-6", "question": "Will fictional Valley United win their next game?", "league": "La Liga", "category": "Sports", "ask": 0.48, "source": "Fictional example"}, {"id": "demo-7", "question": "Will fictional Coast Calcio win their next game?", "league": "Serie A", "category": "Sports", "ask": 0.54, "source": "Fictional example"}, {"id": "demo-8", "question": "Will fictional Forest SC win their next game?", "league": "Bundesliga", "category": "Sports", "ask": 0.6, "source": "Fictional example"}, {"id": "demo-9", "question": "Will fictional Bay Olympique win their next game?", "league": "Ligue 1", "category": "Sports", "ask": 0.66, "source": "Fictional example"}, {"id": "demo-10", "question": "Will fictional Metro FC win their next game?", "league": "MLS", "category": "Sports", "ask": 0.42, "source": "Fictional example"}, {"id": "demo-11", "question": "Will fictional Sierra FC win their next game?", "league": "Liga MX", "category": "Sports", "ask": 0.48, "source": "Fictional example"}, {"id": "demo-12", "question": "Will fictional Continental FC win their next game?", "league": "UEFA Champions League", "category": "Sports", "ask": 0.54, "source": "Fictional example"}, {"id": "demo-economics", "question": "Will fictional Country A report inflation below 3%?", "category": "Economics", "ask": 0.48, "source": "Fictional example"}, {"id": "demo-politics", "question": "Will the fictional Civic Party win its next election?", "category": "Politics", "ask": 0.55, "source": "Fictional example"}, {"id": "demo-tech", "question": "Will fictional Nova Labs launch its device this quarter?", "category": "Technology", "ask": 0.71, "source": "Fictional example"}];
let markets=examples,watchOnly=false;
function renderMarkets(){if(!$('markets'))return;const term=$('search').value.toLowerCase(),cat=$('category').value;const league=$('league').value;const list=markets.filter(m=>m.question.toLowerCase().includes(term)&&(cat==='All'||cat===m.category)&&(m.category!=='Sports'||matchesLeague(m,league))&&(!watchOnly||watches.includes(m.id)));
 $('markets').innerHTML=list.map(m=>`<article class="card"><div class="row"><span class="pill">${esc(m.league||m.category)}</span><span class="small">${esc(m.source)}</span></div><h3>${esc(m.question)}</h3><div class="row"><span class="small">YES ask price</span><span class="value">${m.ask===null?'Unavailable':pct(m.ask)}</span></div><div class="bar"><span style="width:${m.ask===null?0:m.ask*100}%"></span></div><p class="small">Independent model estimate: not available</p><button class="secondary" data-watch="${esc(m.id)}" aria-pressed="${watches.includes(m.id)}">${watches.includes(m.id)?'✓ Watching':'＋ Watch'}</button></article>`).join('')||'<div class="empty">No loaded markets match your filters.</div>';
}
if($('markets')){
 renderMarkets();$('search').addEventListener('input',renderMarkets);$('category').addEventListener('change',()=>{$('league').disabled=!['All','Sports'].includes($('category').value);renderMarkets();});$('league').addEventListener('change',renderMarkets);
 $('watch-only').onclick=()=>{watchOnly=!watchOnly;$('watch-only').setAttribute('aria-pressed',String(watchOnly));renderMarkets();};
 $('markets').onclick=e=>{const b=e.target.closest('[data-watch]');if(!b)return;const id=b.dataset.watch;try{const next=watches.includes(id)?watches.filter(x=>x!==id):[...watches,id].slice(-200);save('unpredicted-watch-v1',next);watches=next;renderMarkets();}catch{$('feed-status').textContent='Browser storage is unavailable. Watchlist was not saved.';}};
 fetch('/api/markets').then(r=>r.ok?r.json():Promise.reject()).then(data=>{if(!data.enabled)return;markets=data.markets;$('feed-label').textContent='AUTHORIZED FEED';$('feed-status').textContent=`Source: ${data.source}. Retrieved ${new Date(data.fetchedAt).toLocaleString()}. Quotes may be delayed. ${data.attribution}`;renderMarkets();}).catch(()=>{});
}
let model=null,datasetHash=null,synthetic=false,lastRun=null;
function demoCSV(){let rows=['date,feature_a,feature_b,outcome'];for(let i=0;i<200;i++){const a=Math.sin(i*2.2)*2,b=Math.cos(i*1.3)*2,p=1/(1+Math.exp(-(a-b*.7)));const outcome=((i*73%199)/199)<p?1:0;rows.push(`${new Date(Date.UTC(2024,0,1+i)).toISOString().slice(0,19)}Z,${a},${b},${outcome}`);}return rows.join('\n');}
async function trainText(text,isDemo){model=null;datasetHash=null;lastRun=null;$('result').hidden=true;const rows=parseCSV(text);model=train(rows);datasetHash=await hash(text);synthetic=isDemo;$('model-report').hidden=false;$('model-report').innerHTML=`<h3>${isDemo?'Synthetic demo':'User data'} · holdout evaluation</h3><p>${model.trainingCount} training rows · ${model.holdoutCount} holdout rows</p><p>Brier: <strong>${model.metrics.brier.toFixed(3)}</strong> · baseline: ${model.metrics.baselineBrier.toFixed(3)}<br>Threshold accuracy: ${pct(model.metrics.accuracy)}</p><p class="small">${isDemo?'Synthetic results are not real-world performance.':'Single holdout evaluation; this does not demonstrate profitability or general reliability.'}</p>`;$('training-status').textContent='Model trained locally. Select trained model mode to use it.';}
if($('simulation')){
 $('train').onclick=async()=>{try{if(!$('rights').checked)throw Error('Confirm permission and feature timing before training.');const f=$('dataset').files[0];if(!f)throw Error('Choose a CSV file.');if(f.size>2e6)throw Error('CSV must be smaller than 2 MB.');await trainText(await f.text(),false);}catch(e){model=null;$('model-report').hidden=true;$('training-status').textContent=e.message;}};
 $('sample').onclick=()=>trainText(demoCSV(),true).catch(e=>$('training-status').textContent=e.message);
 $('dataset').onchange=()=>{model=null;datasetHash=null;$('model-report').hidden=true;$('training-status').textContent='Train the selected dataset before using model mode.';};
 $('mode').onchange=()=>{const isModel=$('mode').value==='model';$('model-fields').hidden=!isModel;$('manual-fields').hidden=isModel;$('probability').required=!isModel;$('feature-a').required=isModel;$('feature-b').required=isModel;$('result').hidden=true;lastRun=null;};
 for(const id of ['sport','question','probability','feature-a','feature-b','quote','trials','seed'])$(id).addEventListener('input',()=>{$('result').hidden=true;lastRun=null;});
 $('simulation').onsubmit=async e=>{e.preventDefault();try{const isModel=$('mode').value==='model';if(!$('question').value.trim())throw Error('Enter a research question.');if(isModel&&!model)throw Error('Train a model first.');const x=[Number($('feature-a').value),Number($('feature-b').value)];const probability=isModel?predict(model,x):Number($('probability').value)/100;const simulation=simulate(probability,Number($('trials').value),Number($('seed').value));const outOfRange=isModel&&x.some((v,j)=>v<model.ranges[j][0]||v>model.ranges[j][1]);
 const quote=$('quote').value===''?null:Number($('quote').value)/100;
 const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),question:$('question').value.trim(),category:$('sport').value,probability,quote,source:isModel?(synthetic?'synthetic-ML-experiment':'user-data-ML-experiment'):'user-probability-assumption',model:isModel?structuredClone(model):null,datasetHash:isModel?datasetHash:null,features:isModel?x:null,simulation,outOfRange,outcome:null,publicationStatus:'personal-local-notebook-not-verified'};
 record.integrityHash=await hash(record);lastRun=record;
 $('result').hidden=false;$('result').innerHTML=`<span class="pill">${isModel?'MACHINE-LEARNING EXPERIMENT':'MANUAL ASSUMPTION'}${isModel&&synthetic?' · SYNTHETIC':''}</span><h2>${esc(record.question)}</h2><div class="kpis"><div><div class="small">${isModel?'MODEL ESTIMATE':'INPUT ASSUMPTION'}</div><div class="value">${pct(probability)}</div></div><div><div class="small">SIMULATED YES FREQUENCY</div><div class="value">${pct(simulation.frequency)}</div></div><div><div class="small">ACTUAL TRIALS EXECUTED</div><div class="value">${simulation.n.toLocaleString()}</div></div></div><p>${simulation.yes.toLocaleString()} YES · ${simulation.no.toLocaleString()} NO · seed ${simulation.seed}. Monte Carlo standard error: ${(simulation.monteCarloSE*100).toFixed(2)} percentage points.</p>${quote!==null?`<p>Difference from entered ask price: ${((probability-quote)*100).toFixed(1)} percentage points. This excludes fees and spread and is not evidence of a profitable edge.</p>`:''}<div class="notice">${outOfRange?'Features are outside the training range. Extrapolation may be unreliable. ':''}These trials sample the probability above; they do not verify it. No profit or outcome is guaranteed. ${isModel&&synthetic?'The model used synthetic data.':''}</div><div class="actions"><button id="download-run">Download evidence JSON</button><button id="save-run" class="secondary">Save to personal notebook</button></div><p class="small">Run time: ${esc(record.createdAt)}. Hash checks record integrity against a trusted copy; it does not prove an independent publication time.</p><p id="run-status" role="status"></p>`;
 $('download-run').onclick=()=>download(`unpredicted-run-${record.id}.json`,record);
 $('save-run').onclick=()=>{try{if(notebook.some(r=>r.id===record.id))throw Error('This run is already saved.');if(notebook.length>=200)throw Error('Notebook limit reached. Export and remove old records first.');const next=[...notebook,{...record,originalEvidence:structuredClone(record)}];save('unpredicted-notebook-v1',next);notebook=next;$('run-status').textContent='Saved in this browser. Export a backup before clearing browser data.';}catch(e){$('run-status').textContent=e.message;}};
 $('sim-status').textContent='Simulation completed.';
 }catch(e){$('sim-status').textContent=e.message;$('result').hidden=true;lastRun=null;}};
}
function renderLedger(){if(!$('ledger'))return;const metrics=ledgerMetrics(notebook);$('ledger').innerHTML=`<p>${notebook.length} saved experiments · ${metrics.count} outcomes entered${metrics.brier!==null?' · Brier '+metrics.brier.toFixed(3):''}. Personal observations only.</p>`+(notebook.length?`<table><thead><tr><th>Research question</th><th>Source</th><th>Estimate</th><th>Created</th><th>Your outcome entry</th></tr></thead><tbody>${notebook.map(r=>`<tr><td>${esc(r.question)}</td><td>${esc(r.source)}</td><td>${pct(r.probability)}</td><td>${esc(r.createdAt)}</td><td><select aria-label="Outcome for ${esc(r.question)}" data-outcome="${esc(r.id)}"><option value="" ${r.outcome===null?'selected':''}>Unresolved</option><option value="1" ${r.outcome===1?'selected':''}>YES occurred</option><option value="0" ${r.outcome===0?'selected':''}>NO occurred</option></select></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No personal experiments saved. Start in the analysis lab.</div>');}
if($('ledger')){renderLedger();$('ledger').onchange=e=>{const id=e.target.dataset.outcome;if(!id)return;try{const next=notebook.map(r=>r.id===id?{...r,outcome:e.target.value===''?null:Number(e.target.value),outcomeEnteredAt:new Date().toISOString()}:r);save('unpredicted-notebook-v1',next);notebook=next;renderLedger();}catch{$('ledger-status').textContent='Could not save outcome. Browser storage is unavailable.';}};$('export-ledger').onclick=()=>download('unpredicted-personal-notebook.json',{exportedAt:new Date().toISOString(),status:'local-user-editable-not-audited',records:notebook});$('clear-ledger').onclick=()=>{if(!confirm('Delete your saved research notebook from this browser? Export a backup first.'))return;try{localStorage.removeItem('unpredicted-notebook-v1');notebook=[];renderLedger();$('ledger-status').textContent='Local notebook deleted.';}catch{$('ledger-status').textContent='Browser storage is unavailable.';}};}

if($('daily-pick')){
 const pick=currentPick(selectedPick);
 if(pick){$('daily-pick').innerHTML=`<span class="pill">${esc(pick.league)}</span><h3>${esc(pick.event)}</h3><p><strong>Selection: ${esc(pick.selection)}</strong></p><p>${esc(pick.rationale)}</p><p class="small">Editor selected · Published ${esc(pick.publishedAt)} · Event begins ${esc(pick.eventStart)}</p><p class="small">This is an editor selection. No AI-generation or model-performance claim is made. No outcome or profit is guaranteed.</p>`;}
}
