import {SOCCER_LEAGUES,sourceHealth} from './soccer-data.js';
import {formCard,escapeHtml as esc,matchDateHtml,timestampHtml} from './team-form.js';
import {teamNameHtml} from './team-colors.js';
import {matchupUrl} from './matchup-data.js';
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search);
let bundle=null;
$('stats-league').innerHTML=Object.keys(SOCCER_LEAGUES).map(l=>`<option>${esc(l)}</option>`).join('');
if(Object.hasOwn(SOCCER_LEAGUES,query.get('league')))$('stats-league').value=query.get('league');
function selectTeams(preferred){const r=bundle?.leagues?.[$('stats-league').value];$('stats-team').innerHTML=(r?.teams||[]).map(t=>`<option>${esc(t.team)}</option>`).join('');$('stats-team').disabled=!r?.teams?.length;if(r?.teams.some(t=>t.team===preferred))$('stats-team').value=preferred;}
function render(){
 const league=$('stats-league').value,team=$('stats-team').value,report=bundle?.leagues?.[league],failed=bundle?.refresh?.[league]?.state==='source-or-validation-error';
 if(!report){$('stats-status').textContent='This league’s statistics are unavailable. No substitute figures are shown.';for(const id of ['stats-profile','stats-upcoming','stats-comparison','stats-source'])$(id).innerHTML='';return;}
 const health=sourceHealth(report),f=report.teams.find(t=>t.team===team);
 $('stats-status').innerHTML=`<span class="pill">${health.resultsDelayed?'DELAYED RESULTS':'DELAYED SNAPSHOT'}</span>${health.snapshotOverdue?' <span class="pill">RETRIEVAL OVERDUE</span>':''}<br>Results through ${matchDateHtml(report.dataThrough)}${health.daysBehind!==null?' · '+health.daysBehind+' days before today':''}<br>Snapshot generated ${timestampHtml(report.generatedAt)} · Season ${esc(report.season)}${failed?'<br><strong>Last source update failed. This is the previous dated snapshot.</strong>':''}`;
 $('stats-profile').innerHTML=f?formCard(f,league):'<div class="card">No team matches this selection.</div>';
 const events=report.upcoming.filter(g=>(g.home===team||g.away===team)&&Date.parse(g.eventStart)>Date.now());
 $('stats-upcoming').innerHTML=`<div class="eyebrow">PROVIDER-MATCHED EVENTS</div><h2>Explore the matchup.</h2>${events.length?events.map(g=>`<article class="card section"><div class="row"><span class="pill">CACHED SCHEDULE</span><span class="small">${timestampHtml(g.eventStart)}</span></div><h3>${teamNameHtml(g.away,league)} at ${teamNameHtml(g.home,league)}</h3><p class="small">The Odds API event identity · Schedule retrieved ${timestampHtml(report.scheduleAsOf)}. Source-result matching uses exact explicit team aliases and the competition-local date. Result-source kickoff time is not verified.</p><a class="button secondary" href="${esc(matchupUrl({...g,id:g.eventId,league}))}">Open matchup →</a></article>`).join(''):'<div class="card"><p>No upcoming provider-matched event in this snapshot. This does not mean the team has no scheduled games.</p><a class="text-link" href="/">Check game center →</a></div>'}`;
 $('stats-comparison').innerHTML=`<div class="eyebrow">LEAGUE WINDOW SUMMARIES</div><h2>Compare the available samples.</h2><p class="small">Up to 10 same-season domestic league games per team. Samples can differ in size. Alphabetical view; this is not an official league table or prediction ranking.</p><div class="card matchup-table"><table><caption>${esc(league)} · Results through ${esc(report.dataThrough||'unavailable')}</caption><thead><tr><th>Team</th><th>Games</th><th>W–D–L</th><th>Goal margin / game</th></tr></thead><tbody>${report.teams.map(t=>`<tr><td><button class="stats-team-link" data-team="${esc(t.team)}">${teamNameHtml(t.team,league)}</button></td><td>${t.count}</td><td>${t.wins}–${t.ties}–${t.losses}</td><td>${t.averageMargin===null?'—':(t.averageMargin>0?'+':'')+t.averageMargin.toFixed(2)}</td></tr>`).join('')}</tbody></table></div>`;
 $('stats-source').innerHTML=`<h2>Source & limitations</h2><p>${esc(report.source.attribution)}</p><p class="small">${esc(report.source.name)} · <a href="${esc(report.source.licenseUrl)}">${esc(report.source.license)}</a> · <a href="${esc(report.source.url)}">Inspect original dataset →</a></p><p>${esc(report.processing.limitations)}</p><p>We retrieve the source daily; community results may update less often. Match dates have day precision. We wait at least 48 hours after a conservative end-of-day UTC cutoff before including results; this is an availability assumption, not a confirmed result-publication timestamp.</p><p>No cup, international, injury, lineup or expected-goals data is used. No soccer model has been trained or published. These statistics do not guarantee future outcomes.</p><details><summary>Dataset provenance</summary><p class="small">SHA-256: ${esc(report.source.sha256)}<br>${report.completedGames} completed league matches in this dated source snapshot.</p></details><a class="text-link" href="/methodology.html">Full methodology →</a>`;
 // Preserve a shareable team selection in the public page address.
 if(window.self===window.top)history.replaceState(null,'',`/stats.html?league=${encodeURIComponent(league)}&team=${encodeURIComponent(team)}`);
}
$('stats-league').onchange=()=>{selectTeams();render();};$('stats-team').onchange=render;
$('stats-comparison').onclick=e=>{const b=e.target.closest('[data-team]');if(!b)return;$('stats-team').value=b.dataset.team;render();$('stats-profile').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
fetch('/data/soccer-context.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(data=>{bundle=data;selectTeams(query.get('team'));render();}).catch(()=>{$('stats-status').textContent='Statistics could not be loaded. Please try again later. No fresh data is claimed.';});
