import {SOCCER_LEAGUES,sourceHealth,soccerInputReadiness} from './soccer-data.js';
import {formCard,escapeHtml as esc,matchDateHtml,timestampHtml} from './team-form.js';
import {teamNameHtml} from './team-colors.js';
import {matchupUrl} from './matchup-data.js';
import {US_STATS_LEAGUES,usStatsReport} from './us-stats.js';
import {upcomingEditorialGames} from './editor-data.js';
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search);
let bundle=null,usReports={},scheduleCache={},renderVersion=0;
const leagues=[...US_STATS_LEAGUES,...Object.keys(SOCCER_LEAGUES)];
$('stats-league').innerHTML=leagues.map(l=>`<option>${esc(l)}</option>`).join('');
if(leagues.includes(query.get('league')))$('stats-league').value=query.get('league');
function selectTeams(preferred){const league=$('stats-league').value,r=US_STATS_LEAGUES.includes(league)?usReports[league]?.teamStatistics:bundle?.leagues?.[league];$('stats-team').innerHTML=(r?.teams||[]).map(t=>`<option>${esc(t.team)}</option>`).join('');$('stats-team').disabled=!r?.teams?.length;if(r?.teams.some(t=>t.team===preferred))$('stats-team').value=preferred;}
function setAddress(league,team){if(window.self===window.top)history.replaceState(null,'',`/stats.html?league=${encodeURIComponent(league)}&team=${encodeURIComponent(team)}`);}
function unavailable(message){$('stats-status').textContent=message;for(const id of ['stats-profile','stats-upcoming','stats-comparison','stats-source'])$(id).innerHTML='';}
async function renderUS(league,team,version){
 const report=usReports[league];let stats;
 try{stats=usStatsReport(report,league);}catch(error){unavailable(error.message);return;}
 const f=stats.teams.find(t=>t.team===team),seasonLabel=league==='NBA'?`${stats.season-1}–${String(stats.season).slice(-2)}`:stats.season;
 $('stats-status').innerHTML=`<span class="pill">DELAYED STATISTICAL SNAPSHOT</span>${stats.snapshotOverdue?' <span class="pill">RETRIEVAL OVERDUE</span>':''}<br>Season ${seasonLabel}${stats.seasonCurrent?'':' · Previous season snapshot'} · Snapshot generated ${timestampHtml(report.generatedAt)}<br>${stats.dataThrough?'Qualifying results through '+timestampHtml(stats.dataThrough)+(stats.daysBehind!==null?' · '+stats.daysBehind+' days before today':''):'No qualifying regular-season results in this season snapshot.'}<br>48-hour availability lag · ${stats.completedGames} included league games. This is not live scoring.`;
 $('stats-profile').innerHTML=f?formCard(f,league):'<div class="card">No team matches this selection.</div>';
 $('stats-comparison').innerHTML=`<div class="eyebrow">LEAGUE WINDOW SUMMARIES</div><h2>Compare the available samples.</h2><p class="small">Up to ${stats.window} same-season regular-season games per team. Alphabetical view; this is not an official standings table, model probability or prediction ranking.</p><div class="card matchup-table"><table><caption>${esc(league)} · Season ${seasonLabel} · 48-hour lag</caption><thead><tr><th>Team</th><th>Games</th><th>W–L${league==='NFL'?'–T':''}</th><th>Point margin / game</th></tr></thead><tbody>${stats.teams.map(t=>`<tr><td><button class="stats-team-link" data-team="${esc(t.team)}">${teamNameHtml(t.team,league)}</button></td><td>${t.count}</td><td>${t.count?`${t.wins}–${t.losses}${league==='NFL'?'–'+t.ties:''}`:'—'}</td><td>${t.averageMargin===null?'—':(t.averageMargin>0?'+':'')+t.averageMargin.toFixed(2)}</td></tr>`).join('')}</tbody></table></div>`;
 $('stats-source').innerHTML=`<h2>Source & limitations</h2><p>${esc(report.source.attribution)}</p><p class="small">${esc(report.source.name)} · <a href="${esc(report.source.licenseUrl)}">${esc(report.source.license)}</a></p><p>${esc(report.processing.limitations)}</p><p>Form uses only the stated season and excludes preseason, playoffs and neutral-site games. Results less than 48 hours before snapshot generation are excluded. Current-season empty samples stay empty. Revised datasets can update earlier scores; retrieval time is not a verified final-publication timestamp.</p><p>These summaries describe results. The ${esc(league)} model is separate and predicts outright wins, not point-spread covers. No spread probability is inferred from average margins.</p><details><summary>Dataset provenance</summary>${report.source.sources.map(s=>`<p class="small"><a href="${esc(s.url)}">Original source${s.season?' · season '+s.season:''} →</a><br>SHA-256: ${esc(s.sha256)}</p>`).join('')}</details><a class="text-link" href="/${league.toLowerCase()}-research.html">Model evidence →</a> · <a class="text-link" href="/methodology.html">Full methodology →</a>`;
 setAddress(league,team);$('stats-upcoming').innerHTML='<div class="card"><p role="status">Checking the provider schedule for this team…</p></div>';
 try{
  if(!scheduleCache[league]||Date.now()-Date.parse(scheduleCache[league].fetchedAt)>3600000){const response=await fetch('/api/games?league='+encodeURIComponent(league));if(!response.ok)throw Error('Unavailable');scheduleCache[league]=await response.json();}
  const feed=scheduleCache[league],canon=t=>league==='NBA'&&t==='Los Angeles Clippers'?'LA Clippers':t;
  const games=upcomingEditorialGames(feed,league).filter(g=>canon(g.home)===team||canon(g.away)===team);
  if(version!==renderVersion)return;
  $('stats-upcoming').innerHTML=`<div class="eyebrow">CACHED PROVIDER SCHEDULE</div><h2>Explore the matchup.</h2><p class="small">Retrieved ${timestampHtml(feed.fetchedAt)} · Cached up to one hour. This is a schedule, not a live-score feed.</p>${games.length?games.map(g=>`<article class="card section"><h3>${teamNameHtml(g.away,league)} at ${teamNameHtml(g.home,league)}</h3><p>${timestampHtml(g.eventStart)}</p><p class="small">Scheduled event information. Open the matchup to check whether a model forecast or editorial selection has actually been published.</p><a class="button secondary" href="${esc(matchupUrl(g))}">Open matchup →</a></article>`).join(''):'<div class="card"><p>No future team event in this provider snapshot. This does not confirm the team has no scheduled games.</p><a class="text-link" href="/">Check game center →</a></div>'}`;
 }catch{if(version===renderVersion)$('stats-upcoming').innerHTML='<div class="card"><p>Provider schedule unavailable or stale. Dated team statistics remain available; no matchup has been invented.</p><a class="text-link" href="/">Check game center →</a></div>';}
}
function render(){
 const version=++renderVersion;if(US_STATS_LEAGUES.includes($('stats-league').value)){renderUS($('stats-league').value,$('stats-team').value,version);return;}
 const league=$('stats-league').value,team=$('stats-team').value,report=bundle?.leagues?.[league],failed=bundle?.refresh?.[league]?.state==='source-or-validation-error';
 if(!report){$('stats-status').textContent='This league’s statistics are unavailable. No substitute figures are shown.';for(const id of ['stats-profile','stats-upcoming','stats-comparison','stats-source'])$(id).innerHTML='';return;}
 const health=sourceHealth(report),f=report.teams.find(t=>t.team===team);
 $('stats-status').innerHTML=`<span class="pill">${health.resultsDelayed?'DELAYED RESULTS':'DELAYED SNAPSHOT'}</span>${health.snapshotOverdue?' <span class="pill">RETRIEVAL OVERDUE</span>':''}<br>Results through ${matchDateHtml(report.dataThrough)}${health.daysBehind!==null?' · '+health.daysBehind+' days before today':''}<br>Snapshot generated ${timestampHtml(report.generatedAt)} · Season ${esc(report.season)}${bundle.refresh?.[league]?.resultsChanged===false?'<br>Source checked successfully; available results have not changed since the previous check.':''}${failed?'<br><strong>Last source update failed. This is the previous dated snapshot.</strong>':''}`;
 $('stats-profile').innerHTML=f?formCard(f,league):'<div class="card">No team matches this selection.</div>';
 const events=report.upcoming.filter(g=>(g.home===team||g.away===team)&&Date.parse(g.eventStart)>Date.now());
 $('stats-upcoming').innerHTML=`<div class="eyebrow">PROVIDER-MATCHED EVENTS</div><h2>Explore the matchup.</h2>${events.length?events.map(g=>{const check=soccerInputReadiness(report,g);return`<article class="card section"><div class="row"><span class="pill">CACHED SCHEDULE</span><span class="small">${timestampHtml(g.eventStart)}</span></div><h3>${teamNameHtml(g.away,league)} at ${teamNameHtml(g.home,league)}</h3><p class="small">The Odds API event identity · Schedule retrieved ${timestampHtml(report.scheduleAsOf)}. Source-result matching uses exact explicit team aliases and the competition-local date. Result-source kickoff time is not verified.</p><div class="notice"><strong>Forecast input check: ${check.status==='blocked'?'blocked':'inputs pass'}</strong>${check.reasons.length?'<ul>'+check.reasons.map(r=>'<li>'+esc(r)+'</li>').join('')+'</ul>':'<p>These input checks pass. Model validation and the publication process are still required.</p>'}<p class="small">No current soccer forecast has been generated or published.</p></div><a class="button secondary" href="${esc(matchupUrl({...g,id:g.eventId,league}))}">Open matchup →</a></article>`;}).join(''):'<div class="card"><p>No upcoming provider-matched event in this snapshot. This does not mean the team has no scheduled games.</p><a class="text-link" href="/">Check game center →</a></div>'}`;
 $('stats-comparison').innerHTML=`<div class="eyebrow">LEAGUE WINDOW SUMMARIES</div><h2>Compare the available samples.</h2><p class="small">Up to 10 same-season domestic league games per team. Samples can differ in size. Alphabetical view; this is not an official league table or prediction ranking.</p><div class="card matchup-table"><table><caption>${esc(league)} · Results through ${esc(report.dataThrough||'unavailable')}</caption><thead><tr><th>Team</th><th>Games</th><th>W–D–L</th><th>Goal margin / game</th></tr></thead><tbody>${report.teams.map(t=>`<tr><td><button class="stats-team-link" data-team="${esc(t.team)}">${teamNameHtml(t.team,league)}</button></td><td>${t.count}</td><td>${t.wins}–${t.ties}–${t.losses}</td><td>${t.averageMargin===null?'—':(t.averageMargin>0?'+':'')+t.averageMargin.toFixed(2)}</td></tr>`).join('')}</tbody></table></div>`;
 $('stats-source').innerHTML=`<h2>Source & limitations</h2><p>${esc(report.source.attribution)}</p><p class="small">${esc(report.source.name)} · <a href="${esc(report.source.licenseUrl)}">${esc(report.source.license)}</a> · <a href="${esc(report.source.url)}">Inspect original dataset →</a></p><p>${esc(report.processing.limitations)}</p><p>We retrieve the source daily; community results may update less often. Match dates have day precision. We wait at least 48 hours after a conservative end-of-day UTC cutoff before including results; this is an availability assumption, not a confirmed result-publication timestamp.</p><p>No cup, international, injury, lineup or expected-goals data is used. A separate historical soccer model has been trained and tested on a later season. These team statistics are descriptive and no current soccer forecasts are published. Historical results do not guarantee future outcomes.</p><details><summary>Dataset provenance</summary><p class="small">SHA-256: ${esc(report.source.sha256)}<br>${report.completedGames} completed league matches in this dated source snapshot.</p></details><a class="text-link" href="/soccer-research.html">Soccer model evidence →</a> · <a class="text-link" href="/methodology.html">Full methodology →</a>`;
 // Preserve a shareable team selection in the public page address.
 setAddress(league,team);
}
$('stats-league').onchange=()=>{selectTeams();render();};$('stats-team').onchange=render;
$('stats-comparison').onclick=e=>{const b=e.target.closest('[data-team]');if(!b)return;$('stats-team').value=b.dataset.team;render();$('stats-profile').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});};
Promise.allSettled(['/data/soccer-context.json','/data/nfl-research.json','/data/nba-research.json'].map(async url=>{const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error();return r.json();})).then(results=>{bundle=results[0].status==='fulfilled'?results[0].value:null;usReports={NFL:results[1].status==='fulfilled'?results[1].value:null,NBA:results[2].status==='fulfilled'?results[2].value:null};selectTeams(query.get('team'));render();});
